[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc5GS5zHOSSN3mtNKQXrIAoHzJ9lf1x3G4iuisMDGcnRlnLQ_NS78lTiXe5QH2NWQuekYg62I3wm76UgamyW9gMMYWLvAGX-ZMrTqyYLKl3gZIBlnUGBE9mdvXrsQZihDF2gCQs4qQos7XFsuz0_NiaL05V1WOy9a8SmifEkbQtTf9g8llbRKcwiZQpq4nkMRxQaCgYKAR4SARcSFQHGX2MiG8HH33iEu8vLzRbwW_RtQg0206","token_type":"Bearer","refresh_token":"1//0gpMF4Ary8oyZCgYIARAAGBASNwF-L9IrmDXNabidVAXtP6SIIyXjHn6TdWroEdMvOG7RsMQlc62Zz5-l8hwAYN_qi5-jE_mxAF4","expiry":"2026-03-01T22:16:09.676493532Z","expires_in":3599}

[dr1]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc4W_FeqPg4thy7IM51tpBH-2VV9He-5Y6X3K5Kl890mn_u01brxeFIGjPMma767QRj2IrjTwx8qPKQzfpMi8rJ7_JQqG1SU3JGQ08Sg3bGDit31IGhkwSZiJkNPRnlH2rl_nHzpzI86ncTuYMf1Txj17v_Q0VzWa23aSoP-XPpT-iW429FljB4fexfF6dhLujUaCgYKAfMSARISFQHGX2MidK8w0pm0c_javUk_LO3EBQ0206","token_type":"Bearer","refresh_token":"1//0gH4sO6uwv5b5CgYIARAAGBASNwF-L9IrOfAUB-px5lx_gwWUdZQjG-e-EZNj1--lPd_BtE9bJGmTz7OnuZqvGufIXc6KmXo29cI","expiry":"2026-03-21T22:47:41.83512796Z","expires_in":3599}

[dr2]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc4xdhm-X-zlKP4U0PI929pmeB_9kzFFSJWjDL8z1iPtgLXqJyzWmZbSf0LVf_W79uF-n6ysYORADavZ7BCfLF9oJsTB-7diWenmIQQR4dCUvImJxX_hDy2Jy6-rK77j8IBNV2S1HEcQ6XmNH_Gu0jD81n7mrnvaDELOITjALiuvFZeBXv1cfwylRRcU209Pzt4aCgYKAYwSARUSFQHGX2Mi7opbml-AlH0m4rsTMW3tdw0206","token_type":"Bearer","refresh_token":"1//0gU0sUTBDBehWCgYIARAAGBASNwF-L9IrYlOAqTTwLcWQFhrxJLU1mWGYJYOMA4YgvfkGxUHgGeFrCWl8aKHFEuIuB0O-_Zyq1WQ","expiry":"2026-03-21T22:50:47.200946818Z","expires_in":3599}

[dr3]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc7GDjNQP5-v-cIPNGYx6ioEBCEbLOaRMpAOL9kcsHrpyPm0QccH13IUhRwzCGw8240ogytZEpHrG5-ZciSimkQCuIa6yHEKvCN6oorkbueDmVQXD5BtFKbFhSV-RCGEtrzmM4TMGeVy8OglElANrEE4W610o4rp_qdFXviGu0WWwJDjecyI9xLjJDwctB4XzuwaCgYKAT4SARcSFQHGX2Mio0WveiWWR4v2ncqC0ondLA0206","token_type":"Bearer","refresh_token":"1//0g1lPHP9UmQUbCgYIARAAGBASNwF-L9IrzeJFgEIlCNvHuw7jbdCFyfMQjIBabkuwYPk3e88VHhvYkbPdpmVaMoysER19162wl0s","expiry":"2026-03-21T22:52:17.0421019Z","expires_in":3599}

[dr4]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc739xFbdOotgkXQfSZRAk2koKhTwQqXbg7XyUjZYj9NOHRrxAi_3fZ8k8-L-NrGfNSQIyn9gpCsLsEaWwwgP7oP0BcFDnfNYyQuwGolju4LbuJAcKH4UvTXVTlBO6pmgJdcpmypqWtYpRp5mydwTFWzcLxsjjSan9Njx8OrvgtvscIsDHpysODoiE7CALVGQWoaCgYKAboSARESFQHGX2MidlyMVO-16ySX_n1B3XLM-g0206","token_type":"Bearer","refresh_token":"1//0gGJbFjc1-SHMCgYIARAAGBASNwF-L9Ir9CNKBG28JLolGDn_v2YztF6ebHrTwQra1nrbcxJXviTwvQgANhz6CLBUkSQ7m5qbaWI","expiry":"2026-03-21T22:53:39.995359982Z","expires_in":3599}
