[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc5GS5zHOSSN3mtNKQXrIAoHzJ9lf1x3G4iuisMDGcnRlnLQ_NS78lTiXe5QH2NWQuekYg62I3wm76UgamyW9gMMYWLvAGX-ZMrTqyYLKl3gZIBlnUGBE9mdvXrsQZihDF2gCQs4qQos7XFsuz0_NiaL05V1WOy9a8SmifEkbQtTf9g8llbRKcwiZQpq4nkMRxQaCgYKAR4SARcSFQHGX2MiG8HH33iEu8vLzRbwW_RtQg0206","token_type":"Bearer","refresh_token":"1//0gpMF4Ary8oyZCgYIARAAGBASNwF-L9IrmDXNabidVAXtP6SIIyXjHn6TdWroEdMvOG7RsMQlc62Zz5-l8hwAYN_qi5-jE_mxAF4","expiry":"2026-03-01T22:16:09.676493532Z","expires_in":3599}

[dr1]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc4IYTvZ47AMaGEruDtl_Bm2RO88GBspyzQIdWwCH0XjnJ4pG3O7DxYff4C3504Es2TNOjADHVvSilvg-_L6uVLJRGHr0CEsrGczic86WUk3xx8ohyFoulZqmMXb21c6k9eEXD9nuNBNrFTQjgbacIrr58ZNCSl8UxGV4aVOW_cbn9RsWQT8y44RlF4jdwFYmNUaCgYKAYgSARcSFQHGX2Mitc0ygtVIyDZ9H43sRRItYw0206","token_type":"Bearer","refresh_token":"1//0g55W--8UOM4jCgYIARAAGBASNwF-L9IrV90MxMO4wOWRGWGdaxhbGJ5JvMg7OkjcPyyJj3dvOj6irT9Jw3RWpe25C9C7X7UnFqY","expiry":"2026-03-20T16:37:10.190633348Z","expires_in":3599}

[dr2]
type = drive
scope = drive
token = {"access_token":"dummy_access_token_2","token_type":"Bearer","refresh_token":"dummy_refresh_token_2","expiry":"2026-03-01T22:16:09.676493532Z","expires_in":3599}

[dr3]
type = drive
scope = drive
token = {"access_token":"dummy_access_token_3","token_type":"Bearer","refresh_token":"dummy_refresh_token_3","expiry":"2026-03-01T22:16:09.676493532Z","expires_in":3599}

[dr4]
type = drive
scope = drive
token = {"access_token":"dummy_access_token_4","token_type":"Bearer","refresh_token":"dummy_refresh_token_4","expiry":"2026-03-01T22:16:09.676493532Z","expires_in":3599}
