[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc5GS5zHOSSN3mtNKQXrIAoHzJ9lf1x3G4iuisMDGcnRlnLQ_NS78lTiXe5QH2NWQuekYg62I3wm76UgamyW9gMMYWLvAGX-ZMrTqyYLKl3gZIBlnUGBE9mdvXrsQZihDF2gCQs4qQos7XFsuz0_NiaL05V1WOy9a8SmifEkbQtTf9g8llbRKcwiZQpq4nkMRxQaCgYKAR4SARcSFQHGX2MiG8HH33iEu8vLzRbwW_RtQg0206","token_type":"Bearer","refresh_token":"1//0gpMF4Ary8oyZCgYIARAAGBASNwF-L9IrmDXNabidVAXtP6SIIyXjHn6TdWroEdMvOG7RsMQlc62Zz5-l8hwAYN_qi5-jE_mxAF4","expiry":"2026-03-01T22:16:09.676493532Z","expires_in":3599}

[dr1]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc4IYTvZ47AMaGEruDtl_Bm2RO88GBspyzQIdWwCH0XjnJ4pG3O7DxYff4C3504Es2TNOjADHVvSilvg-_L6uVLJRGHr0CEsrGczic86WUk3xx8ohyFoulZqmMXb21c6k9eEXD9nuNBNrFTQjgbacIrr58ZNCSl8UxGV4aVOW_cbn9RsWQT8y44RlF4jdwFYmNUaCgYKAYgSARcSFQHGX2Mitc0ygtVIyDZ9H43sRRItYw0206","token_type":"Bearer","refresh_token":"1//0g55W--8UOM4jCgYIARAAGBASNwF-L9IrV90MxMO4wOWRGWGdaxhbGJ5JvMg7OkjcPyyJj3dvOj6irT9Jw3RWpe25C9C7X7UnFqY","expiry":"2026-03-20T16:37:10.190633348Z","expires_in":3599}

[dr2]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc7LfCR4okC2O7-TWK6ZHnL1NkgFkIi9PIGJKAqgCoMZ3sqfchBFxXbFiU5kbw15u3qOUD1MK6-200KuUwlXG9sW-J3v4WkULc85oH1dfDEd8Ok9pxTrgmJlx9w5ojSy3jZW2dSK00ZF6EPOhhzn7cxIL378G0m1WkXAjnZQFRi6z0g7JJGOzRN3yLAhS411mJ0aCgYKAScSARcSFQHGX2MiQj4PQB6RFet3gUDbllX-0Q0206","token_type":"Bearer","refresh_token":"1//0g9OlZUsehrRdCgYIARAAGBASNwF-L9IrfMqJtOyH3KHxwm4uvxHlzB7p8p6CR-g3QrhetGe4gqpZbMKD-viRVW6XFPYv2dzaHrk","expiry":"2026-03-20T16:47:48.049464694Z","expires_in":3599}

[dr3]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc4uexwS6KfwzLqWt8CNt4XpxGZfzgzNTRxDfR3O3QinSE6OVLirvLKarCYtMqpxH8VlS6TQiJoo3IZX5Gr4693hYJ9XN2qh6yNGITrPfnHEJYhVj2F2FSVZxnY14hvtRcdZ6_abE5W4s1yjFYT6FzFZXliQtWagtCgAsGdo5eF0MHnM1dALfPxBVipGZr1Uc6caCgYKAZESARcSFQHGX2Mi9CJ_WSz_T2v4gxVo2PJUug0206","token_type":"Bearer","refresh_token":"1//0gcFgPlNSX5BxCgYIARAAGBASNwF-L9Ir6e_Yn2o05rrQG0oOXxxzriuprAewROVAHEIO7BPl1KCR-4HZGcSMJ6bVRheGNjSPDPg","expiry":"2026-03-20T16:49:47.979099778Z","expires_in":3599}

[dr4]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc4inkCS4ZxEPlvgA3dPXiRqi-RyLt0X1PtxlHiz5ksu-v3PmWsfj9M3PfNlSwW_zYbpyLILfAyYzg47L0Y9HiCrdGEtUigT-ImFtizBxltHNqi_49Va8lLv66DcfTt_TKeFyPNCtuo273hH_nttHLHjJbIIALyE0DC62ns8MtnqxrCXSXezpU1eoaifJd4b3WAaCgYKAVQSARcSFQHGX2MijAgsKFwTrwOf2Zv4MTBZog0206","token_type":"Bearer","refresh_token":"1//0g7UrJUkxTydvCgYIARAAGBASNwF-L9IrgcQHqjzNxf0ez3nvc8TLf6B6SZslx_dhZzFbGYJx8bXvgOxwfPWD9f7m0scGjqRGhf8","expiry":"2026-03-20T16:52:03.480921017Z","expires_in":3599}
